id: product-launch-page
title: Smartwatch Product
prompt: |
  Create a single-page app in a single HTML file with the following requirements:
  - Name: Product Press Release
  - Goal: Showcase a new physical or digital product.
  - Features: Large hero image, specs section, pre-order form.
  - The UI should be modern and product-centric.
screenshot_url: https://cdn.openai.com/devhub/gpt5prompts/product-launch-page.png
tags:
  - landing
